name: 'S&C'
favicon: null
layout_spectrum: 0.2058630008250475
typography_spectrum: 0.11375
title: 'Strength & Conditioning'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9690422457642853
  lightness: 0.9729542674031109
  saturation: 0.4859888425562531
  rhythmicContrast: 0.43610633024945855
purpose: []
